#
# This is a simple awk program which will generate defaultstring.cc
# from an X resource file.
#
#
# "$Id$"
#

#
# insert the "header" for defaultstring.cc
#
BEGIN {
  print "//";
  print "// Do not edit this file.";
  print "// This file is generated automagically from Xdefaults";
  print "// using the awk program found in defresources.awk.";
  print "// This file will be rebuilt when Xdefaults is modified.";
  print "//";
  print "// $Id$";
  print "//";
  print "//\n\n";
  print "char *defaultXResourceString = \"";
}

#
# Echo each line of input (that is not a comment or empty) to stdout.
#
(! /^!/) && (NF != 0)

#
# Insert the "tail" for defresources.cc
#
END {
  print "\";\n";
}
