#
# This is a simple awk program which will generate defaultstring.cc
# from an X resource file.
#

#
# insert the "header" for defaultstring.cc
#
BEGIN {
  print "#ifndef _defaultstring_h";
  print "#define _defaultstring_h";
  print "//";
  print "// Do not edit this file.";
  print "// This file is generated automagically from Xdefaults";
  print "// using the awk program found in defresources.awk.";
  print "// This file will be rebuilt when Xdefaults is modified.";
  print "//\n\n";
  print "char *defaultXResourceString = \"\n";
}

#
# Echo each line of input to stdout.
#
{
  print $0;
}

#
# Insert the "tail" for defresources.cc
#
END {
  print "\";\n";
  print "#endif";
}
